version: "3.8"

services:
    php:
        build: ./docker/php
        volumes:
            - ./app:/var/www/html
        depends_on:
            - db
        networks:
            - symfony

    nginx:
        build: ./docker/nginx
        ports:
            - "80:80"
        volumes:
            - ./app:/var/www/html
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - symfony

    db:
        image: postgres:16-alpine
        container_name: db
        hostname: db
        volumes:
            - ./postgres_data:/var/lib/postgresql/data
        ports:
            - 5432:5432
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        networks:
            - symfony
networks:
    symfony: